variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2 # This should make docker run faster

stages:
  - build
  - report

build:focal:
  image: grouchytoaster/cppbuild:focal
  stage: build
  coverage: /^\s*lines:\s*\d+.\d+\%/
  before_script:
    - cmake --version
    - mkdir build && cd build
  script:
    - CONAN_SYSREQUIRES_SUDO=0 CONAN_SYSREQUIRES_MODE=enabled conan install ..
    - cmake -GNinja -DCMAKE_MODULE_PATH=${PWD} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=yes -DBUILD_COVERAGE=yes ..
    - cmake --build .
    - ctest --output-junit test.xml
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
    - gcovr --root ${CI_PROJECT_DIR} --html --html-details -o coverage.html
  artifacts:
    paths:
      - build
    reports:
      cobertura: build/coverage.xml
      junit: build/test.xml

pages:
  image: tsgkadot/docker-doxygen
  only:
    - master
  needs:
    - build:focal
  stage: report
  script:
    - cp -r ${CI_PROJECT_DIR}/pages ${CI_PROJECT_DIR}/public
    - cp ${CI_PROJECT_DIR}/build/coverage*html ${CI_PROJECT_DIR}/public
    - doxygen Doxyfile
    - mv html public/
  artifacts:
    paths:
      - public
