image: python:bullseye

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y cmake build-essential
    - pip3 install conan
    - conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
    - mkdir build && cd build
    - CONAN_SYSREQUIRES_SUDO=0 CONAN_SYSREQUIRES_MODE=enabled conan install ..
  script:
    - cmake -DCMAKE_MODULE_PATH=${PWD} ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test:
  stage: test
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y cmake
  script:
    - cd build
    - ctest
  needs:
    - build
  artifacts:
    - glot
  #   when: always
  #   reports:
  #     junit: build/libs/cpp-tsdb/dump.xml
