image: grouchytoaster/cppbuild:focal

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 5
  DOCKER_DRIVER: overlay2

stages:
  - build

focal:
  stage: build
  coverage: /^\s*lines:\s*\d+.\d+\%/
  before_script:
    - mkdir build && cd build
    - CONAN_SYSREQUIRES_SUDO=0 CONAN_SYSREQUIRES_MODE=enabled conan install ..
  script:
    - cmake -GNinja -DCMAKE_MODULE_PATH=${PWD} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=yes -DBUILD_COVERAGE=yes ..
    - cmake --build .
    - ctest --output-log test.log
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  artifacts:
    reports:
      cobertura: build/coverage.xml

