name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Provision
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y cmake build-essential python3-pip
          pip3 install conan
          conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
          mkdir build && cd build
      - name: Build
        working-directory: ./build
        run: |
          CONAN_SYSREQUIRES_MODE=enabled conan install ..
          cmake -DCMAKE_MODULE_PATH=${PWD} ..
          cmake --build .
      - name: Test
        working-directory: ./build
        run: ctest
